using System;
using System.Collections.Generic;

namespace AdminService.DBContext
{
    public partial class ConsAdvancedRaw
    {
        public double? Version { get; set; }
        public double? Calendartypeid { get; set; }
        public double? Year { get; set; }
        public double? Month { get; set; }
        public double? Day { get; set; }
        public string Aliastype { get; set; }
        public double? Id { get; set; }
        public string Areacode { get; set; }
        public double? Id2 { get; set; }
        public double? Countryid { get; set; }
        public string Description { get; set; }
        public double? Areacodetypeid { get; set; }
        public string Areacodetype { get; set; }
        public double? Id3 { get; set; }
        public string Calendartype { get; set; }
        public double? Id4 { get; set; }
        public string Country { get; set; }
        public string Id5 { get; set; }
        public string Iso2 { get; set; }
        public string Countryrelevance { get; set; }
        public double? Id6 { get; set; }
        public string Decisionmakingbody { get; set; }
        public double? Id7 { get; set; }
        public double? Organisationid { get; set; }
        public string Detailreference { get; set; }
        public string Id8 { get; set; }
        public string Detailtype { get; set; }
        public string Id9 { get; set; }
        public string Docnamestatus { get; set; }
        public string Id10 { get; set; }
        public string Entryeventtype { get; set; }
        public double? Id11 { get; set; }
        public string Entrylinktypevalues { get; set; }
        public string Exreftypevalues { get; set; }
        public string Featuretype { get; set; }
        public string Id12 { get; set; }
        public string Featuretypegroupid { get; set; }
        public string Featuretypegroup { get; set; }
        public double? Id13 { get; set; }
        public string Idregdocdatetype { get; set; }
        public string Id14 { get; set; }
        public string Idregdoctype { get; set; }
        public string Id15 { get; set; }
        public string Identityfeaturelinktype { get; set; }
        public double? Id16 { get; set; }
        public string Legalbasis { get; set; }
        public string Id17 { get; set; }
        public string Legalbasisshortref { get; set; }
        public string Legalbasistypeid { get; set; }
        public string Sanctionsprogramid { get; set; }
        public string Legalbasistype { get; set; }
        public double? Id18 { get; set; }
        public string List { get; set; }
        public string Id19 { get; set; }
        public string Locparttype { get; set; }
        public string Id20 { get; set; }
        public string Locpartvaluestatus { get; set; }
        public double? Id21 { get; set; }
        public string Locpartvaluetype { get; set; }
        public double? Id22 { get; set; }
        public string Nameparttype { get; set; }
        public string Id23 { get; set; }
        public string Organisation { get; set; }
        public double? Id24 { get; set; }
        public double? Countryid25 { get; set; }
        public string Partysubtype { get; set; }
        public string Id26 { get; set; }
        public string Partytypeid { get; set; }
        public string Partytype { get; set; }
        public string Id27 { get; set; }
        public string Relationquality { get; set; }
        public string Id28 { get; set; }
        public string Relationtype { get; set; }
        public string Id29 { get; set; }
        public string Symmetrical { get; set; }
        public string Reliability { get; set; }
        public string Id30 { get; set; }
        public string Sanctionsprogram { get; set; }
        public string Id31 { get; set; }
        public string Subsidiarybodyid { get; set; }
        public string Sanctionstype { get; set; }
        public string Id32 { get; set; }
        public string Script { get; set; }
        public string Id33 { get; set; }
        public string Scriptcode { get; set; }
        public string Scriptstatus { get; set; }
        public double? Id34 { get; set; }
        public string Subsidiarybody { get; set; }
        public double? Id35 { get; set; }
        public long? Notional { get; set; }
        public double? Decisionmakingbodyid { get; set; }
        public string Supinfotypevalues { get; set; }
        public string Targettypevalues { get; set; }
        public string Validity { get; set; }
        public string Id36 { get; set; }
        public string Id37 { get; set; }
        public string Areacodeid { get; set; }
        public string Featureversionid { get; set; }
        public string Countryid38 { get; set; }
        public string Countryrelevanceid { get; set; }
        public string Locparttypeid { get; set; }
        public string Primarytext { get; set; }
        public string Locpartvaluetypeid { get; set; }
        public string Locpartvaluestatusid { get; set; }
        public string Comment { get; set; }
        public string Value { get; set; }
        public string Idregdocumentid { get; set; }
        public string Id39 { get; set; }
        public string Idregdoctypeid { get; set; }
        public string Identityid { get; set; }
        public string Issuedbycountryid { get; set; }
        public string Issuedinlocationid { get; set; }
        public string Validityid { get; set; }
        public string Comment40 { get; set; }
        public string Idregistrationno { get; set; }
        public string Issuingauthority { get; set; }
        public string Documentednameid { get; set; }
        public string Fixedref { get; set; }
        public string Comment41 { get; set; }
        public string Id42 { get; set; }
        public string Partysubtypeid { get; set; }
        public string Id43 { get; set; }
        public string Fixedref44 { get; set; }
        public string Primary45 { get; set; }
        public string Falsetext { get; set; }
        public string Fixedref46 { get; set; }
        public string Aliastypeid { get; set; }
        public string Primary47 { get; set; }
        public string Lowquality { get; set; }
        public string Id48 { get; set; }
        public string Fixedref49 { get; set; }
        public string Docnamestatusid { get; set; }
        public string Namepartvalue { get; set; }
        public string Namepartgroupid { get; set; }
        public string Scriptid { get; set; }
        public string Scriptstatusid { get; set; }
        public string Acronym { get; set; }
        public string Id50 { get; set; }
        public string Nameparttypeid { get; set; }
        public string Id51 { get; set; }
        public string Featuretypeid { get; set; }
        public string Id52 { get; set; }
        public string Reliabilityid { get; set; }
        public string Comment53 { get; set; }
        public string Calendartypeid54 { get; set; }
        public string Yearfixed { get; set; }
        public string Monthfixed { get; set; }
        public string Dayfixed { get; set; }
        public string Approximate { get; set; }
        public string Yearfixed55 { get; set; }
        public string Monthfixed56 { get; set; }
        public string Dayfixed57 { get; set; }
        public string Year58 { get; set; }
        public string Month59 { get; set; }
        public string Day60 { get; set; }
        public string Year61 { get; set; }
        public string Month62 { get; set; }
        public string Day63 { get; set; }
        public string Approximate64 { get; set; }
        public string Yearfixed65 { get; set; }
        public string Monthfixed66 { get; set; }
        public string Dayfixed67 { get; set; }
        public string Year68 { get; set; }
        public string Month69 { get; set; }
        public string Day70 { get; set; }
        public string Year71 { get; set; }
        public string Month72 { get; set; }
        public string Day73 { get; set; }
        public string Versiondetail { get; set; }
        public string Detailtypeid { get; set; }
        public string Detailreferenceid { get; set; }
        public string Locationid { get; set; }
        public string Identityid74 { get; set; }
        public string Identityfeaturelinktypeid { get; set; }
        public string Id75 { get; set; }
        public string Fromprofileid { get; set; }
        public string Toprofileid { get; set; }
        public string Relationtypeid { get; set; }
        public string Relationqualityid { get; set; }
        public string Former { get; set; }
        public string Sanctionsentryid { get; set; }
        public string Comment76 { get; set; }
        public string Id77 { get; set; }
        public string Profileid { get; set; }
        public string Listid { get; set; }
        public string Id78 { get; set; }
        public string Entryeventtypeid { get; set; }
        public string Legalbasisid { get; set; }
        public string Comment79 { get; set; }
        public string Calendartypeid80 { get; set; }
        public string Year81 { get; set; }
        public string Month82 { get; set; }
        public string Day83 { get; set; }
        public string Id84 { get; set; }
        public string Sanctionstypeid { get; set; }
        public string Calendartypeid85 { get; set; }
        public string Yearfixed86 { get; set; }
        public string Monthfixed87 { get; set; }
        public string Dayfixed88 { get; set; }
        public string Comment89 { get; set; }
        public string Sanctionsentrylinks { get; set; }
    }
}
